import os
import asyncio
from datetime import datetime
from dotenv import load_dotenv
import logging

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mplfinance as mpf

from aiogram import Bot, Dispatcher, types
from aiogram.filters import Command
from apscheduler.schedulers.asyncio import AsyncIOScheduler

load_dotenv()

# === CONFIG ===
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
CHANNEL_ID = int(os.getenv("CHANNEL_ID", 0))
ADMIN_ID = int(os.getenv("ADMIN_ID", 0))
MIN_CONFIDENCE = int(os.getenv("MIN_CONFIDENCE", 80))
TP1_RR = float(os.getenv("TP1_RR", 2))
TP2_RR = float(os.getenv("TP2_RR", 3))

INSTRUMENTS = {
    "GOLD": "GC=F",
    "BTCUSD": "BTC-USD",
    "GBPUSD": "GBPUSD=X",
    "USDJPY": "USDJPY=X",
    "NAS100": "^NDX",
    "US30": "^DJI"
}

logging.basicConfig(level=logging.INFO)
bot = Bot(token=TELEGRAM_TOKEN)
dp = Dispatcher()

scheduler = AsyncIOScheduler()

active_trades = {}

# === CORE FUNCTIONS ===
async def fetch_data(ticker: str, period="60d", interval="30m"):
    df = yf.download(ticker, period=period, interval=interval)
    return df

def atr(df, period=14):
    df['H-L'] = df['High'] - df['Low']
    df['H-PC'] = abs(df['High'] - df['Close'].shift(1))
    df['L-PC'] = abs(df['Low'] - df['Close'].shift(1))
    tr = df[['H-L','H-PC','L-PC']].max(axis=1)
    df['ATR'] = tr.rolling(period).mean()
    return df

def detect_structure(df):
    # Simplified placeholder: BOS/MSS detection
    return "BULL" if df['Close'].iloc[-1] > df['Close'].iloc[-2] else "BEAR"

def detect_order_block(df):
    # Simplified placeholder for OB detection
    return df['Close'].iloc[-1]

def calculate_sl_tp(entry, atr_value, direction):
    if direction == "BUY":
        sl = entry - atr_value
        tp1 = entry + atr_value * TP1_RR
        tp2 = entry + atr_value * TP2_RR
    else:
        sl = entry + atr_value
        tp1 = entry - atr_value * TP1_RR
        tp2 = entry - atr_value * TP2_RR
    return sl, tp1, tp2

async def analyze_and_send_signal(symbol, ticker):
    df = await fetch_data(ticker)
    df = atr(df)
    direction = detect_structure(df)
    entry = detect_order_block(df)
    sl, tp1, tp2 = calculate_sl_tp(entry, df['ATR'].iloc[-1], direction)

    confidence = 85  # placeholder, always >= MIN_CONFIDENCE
    if confidence < MIN_CONFIDENCE:
        return

    # Chart
    fig, axlist = mpf.plot(df[-50:], type='candle', returnfig=True, style='yahoo')
    ax = axlist[0]
    ax.axhline(entry, color='blue', linestyle='--', label='Entry')
    ax.axhline(sl, color='red', linestyle='--', label='SL')
    ax.axhline(tp1, color='green', linestyle='--', label='TP1')
    ax.axhline(tp2, color='green', linestyle='--', label='TP2')
    chart_path = f"{symbol}_chart.png"
    fig.savefig(chart_path)
    plt.close(fig)

    # Message
    msg = f"📈 <b>{symbol} Signal</b>\n"
    msg += f"Direction: {direction}\n"
    msg += f"Entry: {entry:.2f}\nSL: {sl:.2f}\nTP1: {tp1:.2f}\nTP2: {tp2:.2f}\n"
    msg += f"Confidence: {confidence}%\n"
    msg += f"<i>Generated by SMC VIP Bot</i>"

    await bot.send_photo(CHANNEL_ID, photo=open(chart_path, 'rb'), caption=msg, parse_mode="HTML")

# === SCHEDULER ===
async def scan_all():
    for symbol, ticker in INSTRUMENTS.items():
        try:
            await analyze_and_send_signal(symbol, ticker)
        except Exception as e:
            logging.error(f"Error scanning {symbol}: {e}")

# === TELEGRAM COMMANDS ===
@dp.message(Command("status"))
async def cmd_status(message: types.Message):
    if message.from_user.id != ADMIN_ID:
        return
    await message.answer(f"Active Trades: {len(active_trades)}")

@dp.message(Command("help"))
async def cmd_help(message: types.Message):
    await message.answer("/status - show trades\n/help - this message")

# === MAIN ===
async def main():
    scheduler.add_job(scan_all, 'interval', minutes=5)
    scheduler.start()
    await dp.start_polling(bot)

if __name__ == "__main__":
    asyncio.run(main())
